### ISSUE TITLE
Got error when try to run it

### ISSUE THREAD

**Issue by chihhaohuang** [mozilla/observatory-cli#28]
When try to run observatory after installation, I got the following error.
(Centos 6 with nodejs 0.10.46)

/usr/lib/node_modules/observatory-cli/index.js:124
class Scanner {
^^^

SyntaxError: Unexpected reserved word
       at Module._compile (module.js:439:25)
       at Object.Module._extensions..js (module.js:474:10)
       at Module.load (module.js:356:32)
       at Function.Module._load (module.js:312:12)
       at Function.Module.runMain (module.js:497:10)
       at startup (node.js:119:16)
       at node.js:945:3

**Comment by gregglind** [comment]
Observatory requires Node 6.  I will make sure the package.json an other files reflect that.

Thank you for reporting this!

**Comment by gregglind** [comment]
Hm! It already requires "engines: node >=6"

It sounds like `engineStrict` is deprecated.

http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

**Comment by gregglind** [comment]
Needsinfo:  Anyone know how to actually solve this?
