### ISSUE TITLE
/usr/local/lib/node_modules/observatory-cli/index.js:130

### ISSUE THREAD

**Issue by blade1989** [mozilla/observatory-cli#31]
On Ubuntu 16.04.3 LTS, I installed observatory, like so: `npm install -g observatory-cli`. 

When executing the CLI, I get the following:

```
/usr/local/lib/node_modules/observatory-cli/index.js:130
  promiseScan (site, options, method="post") {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
root@eurobytes:~# observatory --help
/usr/local/lib/node_modules/observatory-cli/index.js:130
  promiseScan (site, options, method="post") {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

All the server updates have been installed.

**Comment by nicox** [comment]
Are there any news about this issue? do you know a workaround?

**Comment by lembergerth** [comment]
Same problem here in the official docker image of Ubuntu 16.04. Happy about any suggestions.
